/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "gboy.h"
#include "gbunit.h"
#include "func_offsets.h"
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testWriteVRAM(void);
extern void testWriteStringToVRAM(void);
extern void test_cpu_image_assert(void);
extern void test_memory_access_routines(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test_background_string.c");
  RUN_TEST(testWriteVRAM, 24);
  RUN_TEST(testWriteStringToVRAM, 34);
  RUN_TEST(test_cpu_image_assert, 44);
  RUN_TEST(test_memory_access_routines, 55);

  return (UnityEnd());
}
