; WINDOW_BORDER.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", HOME

; Start of tile array.
WindowBorder::
DB $5A,$3C,$DB,$3C,$18,$FF,$FF,$FF
DB $FF,$FF,$18,$FF,$DB,$3C,$5A,$3C

; End of WINDOW_BORDER.Z80
