; BORDER_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 7
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", HOME

; Start of tile array.
border::
DB $00,$00,$7F,$00,$40,$3F,$5F,$3F
DB $50,$30,$50,$30,$50,$30,$50,$30
DB $00,$00,$FF,$00,$00,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$FE,$00,$02,$FC,$FA,$FC
DB $0A,$0C,$0A,$0C,$0A,$0C,$0A,$0C
DB $0A,$0C,$0A,$0C,$0A,$0C,$0A,$0C
DB $0A,$0C,$0A,$0C,$0A,$0C,$0A,$0C
DB $0A,$0C,$0A,$0C,$0A,$0C,$0A,$0C
DB $FA,$FC,$02,$FC,$FE,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$00,$FF,$FF,$00,$00,$00
DB $50,$30,$50,$30,$50,$30,$50,$30
DB $5F,$3F,$40,$3F,$7F,$00,$00,$00
DB $50,$30,$50,$30,$50,$30,$50,$30
DB $50,$30,$50,$30,$50,$30,$50,$30

; End of BORDER_TILES.Z80
