; SNAKE_BODY_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : Tile-count as Constant.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 10
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", HOME

; Start of tile array.
snake_body::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F
DB $00,$F0,$00,$F0,$00,$F0,$00,$F0
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F
DB $00,$0F,$00,$0F,$00,$0F,$00,$0F

; End of SNAKE_BODY_TILES.Z80
